version: '3.4'

services:
  commentservice:
    image: villsource/commentservice
    environment:
        - DB_CONNECTION_STRING=mongodb://mongo1:50001/comment?replicaSet=my-mongo-set
    networks:
        - service
    depends_on:
      - mongo1
  