version: '3.4'

services:
  mongo1:
    image: mongo
    hostname: mongo1
    volumes:
      - ./mongo_database/data/m1:/data/db
      - ./mongo_database/config/m1:/data/configdb
      - ./mongo_database/log/m1:/data/db/log
      - ./mongo_database/scripts/:/scripts
    environment:
      MONGO_INITDB_DATABASE: admin
      IS_PRIMARY: true
    # ports:
      # - 50001:50001
    command: bash /scripts/endpoint.sh
    networks:
      - service
    restart: always
