version: '3.4'

services:
  authenticationservice:
    image: ghcr.io/untitlecms/authentication-service:v0
    environment: 
      DB_CONNECTION_STRING: Server=sql-server;Database=authentication;User=sa;Password=P@ssword;TrustServerCertificate=True;
      ASPNETCORE_URLS: http://+:80
      ACCESS_TOKEN_LIFETIME: 60
      REFRESH_TOKEN_LIFETIME: 1440
    networks:
      - service
    depends_on:
      - sql-server
