version: '3.4'

services:
  userinfo:
    image: ghcr.io/untitlecms/user-information-service:v0
    environment:
        - DB_CONNECTION_STRING=mongodb://mongo1:50001/comment?replicaSet=my-mongo-set
        - MQ_CONNECTION_STRING=amqp://guest:guest@rabit-mq:5672
    networks:
        - service
    depends_on:
      - mongo1
      - rabit-mq
  