version: '3.4'

services:

  coderunnerservice:
    image: ghcr.io/untitlecms/code-runner-service:v0
    environment:
      PYTHON_SANDBOX_USER: runner
      PYTHON_SANDBOX_HOST: python-slave
      PYTHON_SANDBOX_PORT: 2222
      PYTHON_SANDBOX_KEY: /keys/id_rsa

      JAVA_SANDBOX_USER: runner
      JAVA_SANDBOX_HOST: java-slave
      JAVA_SANDBOX_PORT: 2222
      JAVA_SANDBOX_KEY: /keys/id_rsa

      GCC_SANDBOX_USER: runner
      GCC_SANDBOX_HOST: gcc-slave
      GCC_SANDBOX_PORT: 2222
      GCC_SANDBOX_KEY: /keys/id_rsa

      LOCAL_CODE_STORAGE: /sourcecodes

      EXECUTION_QUOTA: 10
      MAX_EXECUTE_TIME: 30
      CRON_RESET_QUOTA: '0 0 * * * *'
      CACHE_LIFETIME: 1

    volumes:
      - ./CompilerContainer/Keys:/keys
      - ./CompilerContainer/SourceCode:/sourcecodes
    networks:
      - service
      - runner
    restart: always
    # ports:
    #   - 3000:3000
