version: '3.4'

services:

  python-slave:
    image: python-slave
    build:
      context: ./CompilerContainer
      dockerfile: Python.Dockerfile
    environment:
      USER_NAME: runner
    volumes:
      - ./CompilerContainer/Keys:/config/.ssh
      - ./CompilerContainer/SourceCode:/config/sourcecode
    networks:
      - runner
    dns:
      - 1.2.3.4

  java-slave:
    image: java-slave
    build:
      context: ./CompilerContainer
      dockerfile: Java.Dockerfile
    environment:
      USER_NAME: runner
    volumes:
      - ./CompilerContainer/Keys:/config/.ssh
      - ./CompilerContainer/SourceCode:/config/sourcecode
    networks:
      - runner
    dns:
      - 1.2.3.4

  gcc-slave:
    image: ghcr.io/untitlecms/gcc-sandbox:v0
    volumes:
      - ./CompilerContainer/Keys/authorized_keys:/config/authorized_keys
      - ./CompilerContainer/SourceCode:/sourcecode
    networks:
      - runner
    dns:
      - 1.2.3.4
